### ISSUE TITLE
Highlight the option of disabling DHE

### ISSUE THREAD

**Issue by sandstrom** [dadrian/weakdh#2]
Not sure if this is the right place, but I've come across the excellent site https://weakdh.org/. I'm guessing it may be yours.

If so, it would be good if the option, which AWS ELB uses, of simply disabling DHE in the cipher suite (`:!DHE:!EDH`) was more obvious. I find it rather attractive, since most browsers support `ECDHE` anyways.

**Comment by dadrian** [comment]
AWS ELB lets you manually set ciphers? I thought it had high-medium-low settings that you could pick from depending on which version you were using?

**Comment by sandstrom** [comment]
You are right, they are predefined. 

I'm thinking of this:

> The latest set of predefined SSL parameters (2015-05) use ECDHE ciphers, not DHE, and are therefore not vulnerable to Logjam.

Similarly (and obviously you are aware of this) adding `:!DHE:!EDH` to the suite will 'fix' logjam. To me this solution wasn't obvious when looking at the (otherwise excellent) website https://weakdh.org/. So, that's the proposal: make it more obvious that simply disabling DHE is an alternative solution.

**Comment by dadrian** [comment]
Thanks for the heads up. I'll look into updating the website.
